name: Update docs

on:
  push:
    paths:
      - composer.json

jobs:
  update:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create metadata
        run: |
          mkdir -p .github/metadata

          jq -r '
            .require |
            to_entries |
            map(select(.key | contains("/")) |
              {
                Package: ("<b>" + .key + "</b>"),
                Version: .value,
                Packagist: ("https://packagist.org/packages/" + .key)
              }
            )
          ' composer.json > .github/metadata/require.json

      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          commit_message: "Update documentation"
